export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const PLATFORM_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const WORK_ROUTE = '/work'